### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by mcrone** [cov-ert/jclusterfunk#5]
Realise that this may be a bit of a strange request, but could you please put something in the readme on how to install the package for those not using conda etc. I've tried to search around to find out exactly how to install java packages in MacOS without any luck...

**Comment by rambaut** [comment]
Download the binary and put the `jclusterfunk` script and the `jclusterfunk.jar` in a `/bin` directory on your path

**Comment by rambaut** [comment]
Added Install instructions to README

**Comment by mcrone** [comment]
Thanks for the updated installation instructions! I still seem to have problems compiling this with the latest JDK. It seems that your install is designed to use NetBeans as an IDE which handles many of the dependencies that otherwise have been removed from the JDK.

Both of these are no longer included as a part of the JDK:
```
[javac] /Users/blah/Downloads/jclusterfunk-master/src/network/artic/clusterfunk/commands/Collapse.java:3: error: package com.sun.tools.hat.internal.model does not exist
[javac] import com.sun.tools.hat.internal.model.Root;     
```                       


```
[javac] /Users/blah/Downloads/jclusterfunk-master/src/network/artic/clusterfunk/commands/Collapse.java:4: error: package javafx.scene does not exist
[javac] import javafx.scene.Parent;
```

**Comment by rambaut** [comment]
I think those are just accidental includes. Never used NetBeans. I have fixed them in the last commit so if they are causing problems then rebuild using `ant release`. I haven't had a problem running this using `openjdk version "11.0.8-internal" 2020-07-14` though.

**Comment by mcrone** [comment]
Thank you, that worked! I had spent an hour and a half looking at how to include those dependencies and given up. Thanks again!
